### ISSUE TITLE
Update Gear Page

### ISSUE THREAD

**Issue by ntindle** [CodingGarden/coding.garden#16]
> I purchased this pre-built gaming PC on Black Friday in November 2018 for $800. This is a decent mid-tier gaming PC. It is 2 years old, but the specs are more than enough to handle the stream load.

Should probably update this to 5 years old, or replace it if needed.

> USB 2.0 A Male to B Male Cable

> El Gato HD 60 S

> 2015 MacBook Pro

> RK ROYAL KLUDGE RK G68 65% Wireless Mechanical Keyboard, Bluetooth 5.1/2.4G/Wired

Image width overflows container

**Comment by w3cj** [comment]
Info updated and styles should be fixed now.
